spring:
  application:
    name: langchain-spring-boot

langchain4j:
  mcp:
    url: ${mcp_server_url:?????? ?? ??? ??? ??????}
    api-key: ${mcp_api_key:???? ??????????? ???? ?????}
  chat-model:
    ollama:
      base-url: ${llm_url:?????? ? ???}
      model-name: ${llm_model_name:??? ?????? ???}
